# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_ts', models.DateTimeField(auto_now=True, null=True, verbose_name='update timestamp')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='description')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='hostname')),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv4 address')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv6 address')),
                ('macaddress', models.CharField(blank=True, max_length=32, null=True, verbose_name='mac address')),
                ('port', models.IntegerField(default=22, verbose_name='ssh port')),
                ('sudo_username', models.CharField(max_length=32, verbose_name='sudo user')),
                ('sudo_password', models.CharField(max_length=128, verbose_name='password of sudo user')),
                ('processor', models.CharField(blank=True, max_length=64, null=True, verbose_name='processor')),
                ('processor_count', models.IntegerField(blank=True, null=True, verbose_name='processor count')),
                ('product_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='manufacturer model')),
                ('lsb_desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='system distribution information')),
                ('disk_total', models.CharField(blank=True, max_length=64, null=True, verbose_name='disk total')),
                ('memtotal_mb', models.IntegerField(blank=True, null=True, verbose_name='memory total')),
                ('memfree_mb', models.IntegerField(blank=True, null=True, verbose_name='memory free')),
                ('asset_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='asset number')),
                ('status', models.IntegerField(choices=[(0, 'ok'), (1, 'warning'), (2, 'critical'), (3, 'unknown'), (4, 'abandoned'), (5, 'under maintenance')], default=0, verbose_name='current status')),
                ('wk_env', models.IntegerField(choices=[(1, 'development'), (2, 'production')], default=2, verbose_name='working environment')),
                ('mc_type', models.IntegerField(choices=[(1, 'physical machine'), (2, 'virtual machine'), (3, 'router'), (4, 'switch'), (5, 'firewall'), (6, 'unknown')], default=6, verbose_name='machine type')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='serial number')),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'host',
            },
        ),
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_ts', models.DateTimeField(auto_now=True, null=True, verbose_name='update timestamp')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='description')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='hostgroup')),
                ('status', models.IntegerField(choices=[(0, 'ok'), (1, 'warning'), (2, 'critical'), (3, 'unknown'), (4, 'abandoned'), (5, 'under maintenance')], default=0, verbose_name='current status')),
            ],
            options={
                'verbose_name': 'hostgroup',
                'verbose_name_plural': 'hostgroup',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='belong to which hostgroup', to='inventory.Hostgroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
