# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='repo name')),
                ('url', models.CharField(max_length=64, verbose_name='subversion URL to the repository')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('revision', models.CharField(max_length=32, verbose_name='revision')),
                ('dest', models.CharField(max_length=128, verbose_name='absolute path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_author', to=settings.AUTH_USER_MODEL)),
                ('hostgroups', models.ManyToManyField(blank=True, to='inventory.Hostgroup')),
                ('hosts', models.ManyToManyField(blank=True, to='inventory.Host')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repository',
            },
        ),
        migrations.CreateModel(
            name='RepoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_code', models.IntegerField(default=0, verbose_name='play return code')),
                ('results', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('executor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo_executor', to=settings.AUTH_USER_MODEL, verbose_name='operation executor')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.Repo')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunnerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('module_name', models.CharField(max_length=64)),
                ('become_user', models.CharField(default='root', max_length=64)),
                ('become_method', models.IntegerField(choices=[(0, 'sudo'), (1, 'su'), (2, 'pbrun'), (3, 'pfexec'), (4, 'runas'), (5, 'doas'), (6, 'dzdo')], default=1)),
                ('remote_user', models.CharField(default='root', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ShellResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_code', models.IntegerField(default=0, verbose_name='play return code')),
                ('results', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('shell', models.TextField()),
                ('executor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_executor', to=settings.AUTH_USER_MODEL, verbose_name='operation executor')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='repo',
            name='opts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.RunnerOption'),
        ),
    ]
