# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_code', models.IntegerField(default=0, verbose_name='play return code')),
                ('results', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('cmd', models.TextField()),
                ('executor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmd_executor', to=settings.AUTH_USER_MODEL, verbose_name='operation executor')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shellresult',
            name='executor',
        ),
        migrations.DeleteModel(
            name='ShellResult',
        ),
    ]
